baseURL = "https://chrishorner.codes"
languageCode = "en-au"
title = "Chris Horner"
disableKinds = ["taxonomy"]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[params.author]
  name = "Chris Horner"
  email = "chris [at] horner [dot] chat"
