[build.environment]
HUGO_VERSION = "0.157.0"

[build]
publish = "public"
command = """\
  git config core.quotepath false && \
  hugo build --gc --minify --baseURL "${URL}"
  """

[[redirects]]
  from = "https://chrishorner.dev/*"
  to = "https://chrishorner.codes/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://chrishorner.netlify.com/*"
  to = "https://chrishorner.codes/:splat"
  status = 301
  force = true
